# ansible-playbook ~/.bootstrap/install_docker.yml -i ~/.bootstrap/inventory.ini --ask-become-pass 
# For localhost:
#   ansible-playbook -i localhost, -c local install_docker.yml --ask-become-pass
# Another option for localhost is to use a localhost_inventory.yml
#   ansible-playbook -i localhost_inventory.yml install_docker.yml --ask-become-pass
#
# For networked machines (using inventory.yml)
#   ansible-playbook -i linux_inventory.yml install_docker.yml --ask-become-pass

# Note:
#   It is not necessary to have --ask-become-pass if the user does not need password to become root.
---
- name: Install Snap packages
  hosts: all
  become: true
  tasks:
    - name: Ensure Snap is installed
      ansible.builtin.apt:
        name: snapd
        state: present

    - name: Ensure snapd service is running
      ansible.builtin.service:
        name: snapd
        state: started
        enabled: true

    - name: Install Snap packages
      become: true
      ansible.builtin.command: snap install {{ item.name }} {{ item.extra_args | default('') }}
      loop:
        - { name: "bw" }
        - { name: "chezmoi", extra_args: "--classic" }
        - { name: "alacritty", extra_args: "--classic" }
        - { name: "gtk-common-themes" }
        - { name: "icloud-for-linux" }
        - { name: "kompare" }
        - { name: "whatsdesk" }
        - { name: "zig", extra_args: "--classic --beta" }
