# ansible-playbook -i ~/.bootstrap/inventory.ini ~/.bootstrap/install_starship.yml --ask-become-pass
---
- name: Install and Configure Starship Prompt on Linux
  hosts: all
  become: true 
  vars:
    # Temporary directory for installation files
    starship_temp_dir: "/tmp/starship_install"

  tasks:
    - name: Ensure required packages are installed
      package:
        name:
          - curl
        state: present

    - name: Create temporary directory for Starship installation
      file:
        path: "{{ starship_temp_dir }}"
        state: directory
        mode: '0755'

    - name: Download and run Starship install script
      shell: |
        curl -sS https://starship.rs/install.sh | sh -s -- --yes --bin-dir {{ starship_temp_dir }}
      args:
        creates: "{{ starship_temp_dir }}/starship"
      environment:
        CARGO_HOME: "{{ starship_temp_dir }}/cargo"
      register: starship_install
      ignore_errors: yes

    - name: Check if Starship was installed successfully
      stat:
        path: "{{ starship_temp_dir }}/starship"
      register: starship_binary

    - name: Fail if Starship installation failed
      fail:
        msg: "Starship installation script failed."
      when: not starship_binary.stat.exists

    - name: Move Starship binary to /usr/local/bin/
      copy:
        src: "{{ starship_temp_dir }}/starship"
        dest: "/usr/local/bin/starship"
        mode: '0755'
        owner: root
        group: root
      notify: Restart Shell

    - name: Ensure /usr/local/bin is in PATH for all users
      lineinfile:
        path: /etc/profile
        regexp: '^export PATH=.*:/usr/local/bin'
        line: 'export PATH=$PATH:/usr/local/bin'
        state: present

    - name: Verify Starship installation
      command: /usr/local/bin/starship --version
      register: starship_version
      changed_when: false
      failed_when: starship_version.rc != 0

    - name: Display installed Starship version
      debug:
        msg: "Starship installed successfully: {{ starship_version.stdout }}"

