#
# For localhost:
#   ansible-playbook -i localhost, -c local install_cloudflared.yml --ask-become-pass
# Another option for localhost is to use a localhost_inventory.yml
#   ansible-playbook -i inventory_local.ini install_cloudflared.yml --ask-become-pass
#
# For networked machines (using inventory_net.ini)
#   ansible-playbook -i inventory_net.ini install_cloudflared.yml --ask-become-pass

# Note:
#   It is not necessary to have --ask-become-pass if the user does not need password to become root.
#

---
- name: Set up Cloudflared repository and install cloudflared
  hosts: all
  become: true
  tasks:
    - name: Ensure the GPG directory exists
      file:
        path: /usr/share/keyrings
        state: directory
        mode: "0755"

    - name: Download Cloudflare GPG key
      get_url:
        url: https://pkg.cloudflare.com/cloudflare-main.gpg
        dest: /usr/share/keyrings/cloudflare-main.gpg
        mode: "0644"

    - name: Add Cloudflared APT repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared bookworm main"
        state: present
        filename: "cloudflared"

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Cloudflared
      apt:
        name: cloudflared
        state: present
        update_cache: yes
