# 
# ansible-playbook ~/.bootstrap/install_essentials.yml -i ~/.bootstrap/inventory_no_root.ini --ask-become-pass
---
- name: Install essential packages
  hosts: localhost
  remote_user: gtoscano
  become: false 
  vars:
    user: gtoscano
    home_dir: "/home/{{ user }}"
  tasks:
    - name: Update APT cache
      become: true
      ansible.builtin.apt:
        update_cache: yes

    - name: Install packages
      become: true
      ansible.builtin.apt:
        name:
          - age
          - autoconf
          - bzip2
          - fd-find
          - ffmpeg
          - fish
          - fzf
          - gh
          - git
          - gnome-tweaks
          - gcc
          - g++
          - htop
          - libbz2-dev
          - libreadline-dev
          - libssl-dev
          - libffi-dev
          - liblzma-dev
          - libncurses5-dev
          - libnsl2
          - luarocks
          - make
          - ripgrep
          - patch
          - sudo
          - tmux
          - tk-dev
          - uuid-dev
          - zlib1g
          - zlib1g-dev
          - zsh
        state: present

    - name: Source .zshrc (optional immediate effect for current session)
      become: false 
      shell: source "{{ home_dir }}/.zshrc"
      args:
        executable: /bin/zsh
      register: source_zshrc
