# ansible-playbook ~/.bootstrap/install_flatpaks.yml -i ~/.bootstrap/inventory_no_root.ini --ask-become-pass --extra-vars
#
#
---
- name: Install Flatpak packages
  hosts: localhost
  become: false 
  vars:
    user: gtoscano
    home_dir: "/home/{{ user }}"
    flatpak_user_dir: "{{ home_dir }}/.local/share/flatpak"
  tasks:
    - name: Ensure Flatpak is installed
      become: true 
      ansible.builtin.apt:
        name: flatpak
        state: present

    - name: Install Flatpak plugin for GNOME Software (optional, improves GUI integration)
      become: true 
      ansible.builtin.apt:
        name: gnome-software-plugin-flatpak
        state: present

    - name: Add Flathub repository for the user
      become: false
      ansible.builtin.command: >
        flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      args:
        creates: "{{ flatpak_user_dir }}/repo/flathub"
      become_user: "{{ user }}"

    - name: Install Flatpak packages for the user
      become: false
      ansible.builtin.command: >
        flatpak --user install -y flathub {{ item }}
      loop:
        - com.bitwarden.desktop
        - com.belmoussaoui.Decoder
        - com.github.marktext.marktext
        - com.github.jeromerobert.pdfarranger
        - com.google.Chrome
        - com.nextcloud.desktopclient.nextcloud
        - com.obsproject.Studio
        - io.dbeaver.DBeaverCommunity
        - com.sublimetext.three
        - org.flameshot.Flameshot
        - org.videolan.VLC
        - org.gimp.GIMP
        - org.gnome.meld
        - us.zoom.Zoom
        - org.libreoffice.LibreOffice
      become_user: "{{ user }}"
