# For localhost:
#   ansible-playbook -i localhost, -c local install_essentials.yml --ask-become-pass
# Another option for localhost is to use a localhost_inventory.yml
#   ansible-playbook -i inventory_local.ini install_essentials.yml --ask-become-pass
#
# For networked machines (using inventory_net.ini)
#   ansible-playbook -i inventory_net.ini install_essentials.yml --ask-become-pass

# Note:
#   It is not necessary to have --ask-become-pass if the user does not need password to become root.
#
---
- name: Install essential packages and configure sudo
  hosts: all
  become: true
  vars:
    user: "{{ ansible_user }}"
    home_dir: "/home/{{ ansible_user }}"
  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install packages
      ansible.builtin.apt:
        name:
          - age
          - autoconf
          - btop
          - bzip2
          - fd-find
          - ffmpeg
          - fish
          - fzf
          - gh
          - git
          - gnome-tweaks
          - gcc
          - g++
          - htop
          - libbz2-dev
          - libreadline-dev
          - libssl-dev
          - libffi-dev
          - liblzma-dev
          - libncurses5-dev
          - libnsl2
          - luarocks
          - make
          - ripgrep
          - patch
          - tmux
          - tk-dev
          - uuid-dev
          - yadm
          - zlib1g
          - zlib1g-dev
          - zsh
          - zsh-autosuggestions
          - zsh-syntax-highlighting
        state: present

    - name: Ensure the sudo group exists
      ansible.builtin.group:
        name: sudo
        state: present

        # - name: Add user to sudo group
        #   ansible.builtin.user:
        #     name: "{{ user }}"
        #     groups: sudo
        #     append: true

        # - name: Configure passwordless sudo for user
        #   ansible.builtin.lineinfile:
        #     path: /etc/sudoers.d/99-{{ user }}
        #     create: yes
        #     mode: '0440'
        #     line: "{{ user }} ALL=(ALL) NOPASSWD: ALL"

        # - name: Notify user about passwordless sudo
        #   ansible.builtin.debug:
        #     msg: "User {{ user }} has been added to the sudo group with passwordless privileges."
