#
---
- import_playbook: install_essentials.yml
- import_playbook: install_neovim.yml
- import_playbook: install_snaps.yml
- import_playbook: install_flatpaks.yml
- import_playbook: install_docker.yml
- import_playbook: install_cloudflared.yml
- import_playbook: install_ghostty.yml
- import_playbook: install_regolith_bookworm.yml
- import_playbook: install_starship.yml
